export var StationIdentifier;
(function (StationIdentifier) {
    StationIdentifier["E1"] = "e1";
    StationIdentifier["E2"] = "e2";
    StationIdentifier["E3"] = "e3";
    StationIdentifier["E4"] = "e4";
    StationIdentifier["E5"] = "e5";
    StationIdentifier["E6"] = "e6";
    StationIdentifier["E7"] = "e7";
    StationIdentifier["E8"] = "e8";
    StationIdentifier["E9"] = "e9";
    StationIdentifier["E10"] = "e10";
    StationIdentifier["E11"] = "e11";
    StationIdentifier["E12"] = "e12";
    StationIdentifier["E13"] = "e13";
    StationIdentifier["E14"] = "e14";
})(StationIdentifier || (StationIdentifier = {}));
export var MetroLine;
(function (MetroLine) {
    MetroLine["Blue"] = "blue";
    MetroLine["Yellow"] = "yellow";
    MetroLine["Red"] = "red";
    MetroLine["Green"] = "green";
})(MetroLine || (MetroLine = {}));
export const TRAIN_SPEED_IN_KILOMETERS_PER_HOUR = 30;
export const LINE_EXCHANGE_TIME_IN_MINUTES = 4;
export const STATIONS = {
    [StationIdentifier.E1]: {
        identifier: StationIdentifier.E1,
        estimatedDistances: {
            e1: 0,
            e2: 10,
            e3: 18.5,
            e4: 24.8,
            e5: 36.4,
            e6: 38.8,
            e7: 35.8,
            e8: 25.4,
            e9: 17.6,
            e10: 9.1,
            e11: 16.7,
            e12: 27.3,
            e13: 27.6,
            e14: 29.8
        },
        realDistances: {
            e1: null,
            e2: 10,
            e3: null,
            e4: null,
            e5: null,
            e6: null,
            e7: null,
            e8: null,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Blue],
    },
    [StationIdentifier.E2]: {
        identifier: StationIdentifier.E2,
        estimatedDistances: {
            e1: 10,
            e2: 0,
            e3: 8.5,
            e4: 14.8,
            e5: 26.6,
            e6: 29.1,
            e7: 26.1,
            e8: 17.3,
            e9: 10,
            e10: 3.5,
            e11: 15.5,
            e12: 20.9,
            e13: 19.1,
            e14: 21.8
        },
        realDistances: {
            e1: 10,
            e2: null,
            e3: 8.5,
            e4: null,
            e5: null,
            e6: null,
            e7: null,
            e8: null,
            e9: 10,
            e10: 3.5,
            e11: null,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Blue, MetroLine.Yellow],
    },
    [StationIdentifier.E3]: {
        identifier: StationIdentifier.E3,
        estimatedDistances: {
            e1: 18.5,
            e2: 8.5,
            e3: 0,
            e4: 6.3,
            e5: 18.2,
            e6: 20.6,
            e7: 17.6,
            e8: 13.6,
            e9: 9.4,
            e10: 10.3,
            e11: 19.5,
            e12: 19.1,
            e13: 12.1,
            e14: 16.6
        },
        realDistances: {
            e1: null,
            e2: 8.5,
            e3: null,
            e4: 6.3,
            e5: null,
            e6: null,
            e7: null,
            e8: null,
            e9: 9.4,
            e10: null,
            e11: null,
            e12: null,
            e13: 18.7,
            e14: null,
        },
        lines: [MetroLine.Blue, MetroLine.Red],
    },
    [StationIdentifier.E4]: {
        identifier: StationIdentifier.E4,
        estimatedDistances: {
            e1: 24.8,
            e2: 14.8,
            e3: 6.3,
            e4: 0,
            e5: 12,
            e6: 14.4,
            e7: 11.5,
            e8: 12.4,
            e9: 12.6,
            e10: 16.7,
            e11: 23.6,
            e12: 18.6,
            e13: 10.6,
            e14: 15.4
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: 6.3,
            e4: null,
            e5: 13,
            e6: null,
            e7: null,
            e8: 15.3,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: 12.8,
            e14: null,
        },
        lines: [MetroLine.Blue, MetroLine.Green],
    },
    [StationIdentifier.E5]: {
        identifier: StationIdentifier.E5,
        estimatedDistances: {
            e1: 36.4,
            e2: 26.6,
            e3: 18.2,
            e4: 12,
            e5: 0,
            e6: 3,
            e7: 2.4,
            e8: 19.4,
            e9: 23.3,
            e10: 28.2,
            e11: 34.2,
            e12: 24.8,
            e13: 14.5,
            e14: 17.9
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: null,
            e4: 13,
            e5: null,
            e6: 3,
            e7: 2.4,
            e8: 30,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Blue, MetroLine.Yellow],
    },
    [StationIdentifier.E6]: {
        identifier: StationIdentifier.E6,
        estimatedDistances: {
            e1: 38.8,
            e2: 29.1,
            e3: 20.6,
            e4: 14.4,
            e5: 3,
            e6: 0,
            e7: 3.3,
            e8: 22.3,
            e9: 25.7,
            e10: 30.3,
            e11: 36.7,
            e12: 27.6,
            e13: 15.2,
            e14: 18.2
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: null,
            e4: null,
            e5: 3,
            e6: null,
            e7: null,
            e8: null,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Blue],
    },
    [StationIdentifier.E7]: {
        identifier: StationIdentifier.E7,
        estimatedDistances: {
            e1: 35.8,
            e2: 26.1,
            e3: 17.6,
            e4: 11.5,
            e5: 2.4,
            e6: 3.3,
            e7: 0,
            e8: 20,
            e9: 23,
            e10: 27.3,
            e11: 34.2,
            e12: 25.7,
            e13: 12.4,
            e14: 15.6
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: null,
            e4: null,
            e5: 2.4,
            e6: null,
            e7: null,
            e8: null,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Yellow],
    },
    [StationIdentifier.E8]: {
        identifier: StationIdentifier.E8,
        estimatedDistances: {
            e1: 25.4,
            e2: 17.3,
            e3: 13.6,
            e4: 12.4,
            e5: 19.4,
            e6: 22.3,
            e7: 20,
            e8: 0,
            e9: 8.2,
            e10: 20.3,
            e11: 16.1,
            e12: 6.4,
            e13: 22.7,
            e14: 27.6
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: null,
            e4: 15.3,
            e5: 30,
            e6: null,
            e7: null,
            e8: null,
            e9: 9.6,
            e10: null,
            e11: null,
            e12: 6.4,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Yellow, MetroLine.Green],
    },
    [StationIdentifier.E9]: {
        identifier: StationIdentifier.E9,
        estimatedDistances: {
            e1: 17.6,
            e2: 10,
            e3: 9.4,
            e4: 12.6,
            e5: 23.3,
            e6: 25.7,
            e7: 23,
            e8: 8.2,
            e9: 0,
            e10: 13.5,
            e11: 11.2,
            e12: 10.9,
            e13: 21.2,
            e14: 26.6
        },
        realDistances: {
            e1: null,
            e2: 10,
            e3: 9.4,
            e4: null,
            e5: null,
            e6: null,
            e7: null,
            e8: 9.6,
            e9: null,
            e10: null,
            e11: 12.2,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Yellow, MetroLine.Red],
    },
    [StationIdentifier.E10]: {
        identifier: StationIdentifier.E10,
        estimatedDistances: {
            e1: 9.1,
            e2: 3.5,
            e3: 10.3,
            e4: 16.7,
            e5: 28.2,
            e6: 30.3,
            e7: 27.3,
            e8: 20.3,
            e9: 13.5,
            e10: 0,
            e11: 17.6,
            e12: 24.2,
            e13: 18.7,
            e14: 21.2
        },
        realDistances: {
            e1: null,
            e2: 3.5,
            e3: null,
            e4: null,
            e5: null,
            e6: null,
            e7: null,
            e8: null,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Yellow],
    },
    [StationIdentifier.E11]: {
        identifier: StationIdentifier.E11,
        estimatedDistances: {
            e1: 16.7,
            e2: 15.5,
            e3: 19.5,
            e4: 23.6,
            e5: 34.2,
            e6: 36.7,
            e7: 34.2,
            e8: 16.1,
            e9: 11.2,
            e10: 17.6,
            e11: 0,
            e12: 14.2,
            e13: 31.5,
            e14: 35.5
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: null,
            e4: null,
            e5: null,
            e6: null,
            e7: null,
            e8: null,
            e9: 12.2,
            e10: null,
            e11: null,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Red],
    },
    [StationIdentifier.E12]: {
        identifier: StationIdentifier.E12,
        estimatedDistances: {
            e1: 27.3,
            e2: 20.9,
            e3: 19.1,
            e4: 18.6,
            e5: 24.8,
            e6: 27.6,
            e7: 25.7,
            e8: 6.4,
            e9: 10.9,
            e10: 24.2,
            e11: 14.2,
            e12: 0,
            e13: 28.8,
            e14: 33.6
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: null,
            e4: null,
            e5: null,
            e6: null,
            e7: null,
            e8: 6.4,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: null,
            e14: null,
        },
        lines: [MetroLine.Green],
    },
    [StationIdentifier.E13]: {
        identifier: StationIdentifier.E13,
        estimatedDistances: {
            e1: 27.6,
            e2: 19.1,
            e3: 12.1,
            e4: 10.6,
            e5: 14.5,
            e6: 15.2,
            e7: 12.4,
            e8: 22.7,
            e9: 21.2,
            e10: 18.7,
            e11: 31.5,
            e12: 28.8,
            e13: 0,
            e14: 5.1
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: 18.7,
            e4: 12.8,
            e5: null,
            e6: null,
            e7: null,
            e8: null,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: null,
            e14: 5.1,
        },
        lines: [MetroLine.Red, MetroLine.Green],
    },
    [StationIdentifier.E14]: {
        identifier: StationIdentifier.E14,
        estimatedDistances: {
            e1: 29.8,
            e2: 21.8,
            e3: 16.6,
            e4: 15.4,
            e5: 17.9,
            e6: 18.2,
            e7: 15.6,
            e8: 27.6,
            e9: 26.6,
            e10: 21.2,
            e11: 35.5,
            e12: 33.6,
            e13: 5.1,
            e14: 0
        },
        realDistances: {
            e1: null,
            e2: null,
            e3: null,
            e4: null,
            e5: null,
            e6: null,
            e7: null,
            e8: null,
            e9: null,
            e10: null,
            e11: null,
            e12: null,
            e13: 5.1,
            e14: null,
        },
        lines: [MetroLine.Green],
    }
};
